use super::*;

/// Returns true if the prompt_id was generated by the shell for a
/// server-initiated auto-wake turn (background task or subagent completion).
pub(crate) fn is_server_initiated_prompt(prompt_id: &str) -> bool {
    xai_grok_shell::session::PromptOrigin::from_prompt_id(prompt_id).is_synthetic()
}

/// Returns true if the prompt_id is a scheduled-task (`/loop`) fire.
///
/// Cron turns are synthetic (so [`is_server_initiated_prompt`] is also true for
/// them), but UNLIKE auto-wake / subagent-completion turns they are
/// CLIENT-driven via `MvpAgent::prompt()` and therefore DO emit a matching
/// `x.ai/session/prompt_complete` turn-end signal. A viewer can thus safely
/// enter `TurnRunning` for them (the exit exists, so it won't strand) — which is
/// what lets the dashboard show a running `/loop` session as Working.
pub(crate) fn is_scheduler_fired_prompt(prompt_id: &str) -> bool {
    matches!(
        xai_grok_shell::session::PromptOrigin::from_prompt_id(prompt_id),
        xai_grok_shell::session::PromptOrigin::SchedulerFired
    )
}

/// Returns true for the auto-wake turn families (`task-completed-…`,
/// `subagent-completed-…`, `notifications-…`). These run non-adopted — no
/// `PromptResponse`, no viewer finalize — so their durable `TurnCompleted` is
/// the only signal marking the back-to-idle point (see [`finish_wake_turn`];
/// wake turns close markerless). Deliberately narrower than "non-adopted
/// synthetic": goal turns render through the goal chip/loop chrome and
/// `plan-resume-…` keeps its own markerless shape.
pub(crate) fn is_wake_prompt(prompt_id: &str) -> bool {
    matches!(
        xai_grok_shell::session::PromptOrigin::from_prompt_id(prompt_id),
        xai_grok_shell::session::PromptOrigin::TaskCompleted { .. }
            | xai_grok_shell::session::PromptOrigin::SubagentCompleted { .. }
            | xai_grok_shell::session::PromptOrigin::WorkflowCompleted { .. }
            | xai_grok_shell::session::PromptOrigin::NotificationDrain
    )
}

/// Whether a running `prompt_id` is adoptable — i.e. safe to bind as the
/// viewer's `current_prompt_id` and show as a live `TurnRunning`. The invariant:
/// adoptable iff the turn emits a terminal `x.ai/session/prompt_complete`, the
/// only non-interactive way a viewer leaves `TurnRunning`. That holds for
/// user-driven turns and `/loop` (`scheduler-fired-…`) fires — both run via
/// `MvpAgent::prompt()` — and is false for actor-run synthetic turns
/// (task-completed / subagent-completion / notification-drain / goal-*), which
/// have no such exit, so adopting one strands the viewer in `TurnRunning`.
///
/// This is the pure pid-only synthetic-turn guard. It serves the live-delta
/// viewer gate and the `queue/changed` turn-start shim (the latter negated, as a
/// skip) directly. The two adoption-on-load paths (`SessionLoaded` in
/// `dispatch.rs`, the reconnect-reload `finalize_reload_and_maybe_adopt`) instead
/// call the agent-aware [`AgentView::should_adopt_running_prompt`], which ANDs
/// this guard with "not terminal-in-replay" so an already-ended turn replayed on
/// reattach is not re-adopted.
///
/// [`AgentView::should_adopt_running_prompt`]: crate::app::agent_view::AgentView::should_adopt_running_prompt
pub(crate) fn should_adopt_running_prompt(prompt_id: &str) -> bool {
    !is_server_initiated_prompt(prompt_id) || is_scheduler_fired_prompt(prompt_id)
}

/// Compute the monotonic anchor a VIEWER should use as its turn-start time.
///
/// A viewer adopts the driver's turn mid-stream, so stamping `Instant::now()`
/// would make its elapsed counter — and the final "Worked for X" marker
/// (both read off `turn_started_at` via [`AgentView::turn_elapsed`]) — read
/// LESS than the driver's by the time-to-first-delta. The shell records the
/// authoritative wall-clock turn start in `meta.turnStartMs` (UTC ms, stamped
/// at the top of the turn), so back-date the anchor from it; the viewer's
/// elapsed then matches the driver's, both live and on completion. Falls back
/// to `now` when `turnStartMs` is absent (older shell) or the wall clock is
/// skewed forward.
pub(super) fn viewer_turn_anchor(turn_start_ms: Option<i64>) -> std::time::Instant {
    let now = std::time::Instant::now();
    let Some(start_ms) = turn_start_ms else {
        return now;
    };
    let elapsed_ms = chrono::Utc::now()
        .timestamp_millis()
        .saturating_sub(start_ms);
    if elapsed_ms <= 0 {
        return now;
    }
    now.checked_sub(std::time::Duration::from_millis(elapsed_ms as u64))
        .unwrap_or(now)
}

/// Close out a wake turn: markerless, but the stream must be finished here —
/// wake turns skip `PromptResponse`, so this is the only flush site for an
/// in-flight streamed entry (dead wakes included). Leaves a real turn's
/// stop-hook stash pending for its own marker rail.
pub(super) fn finish_wake_turn(agent: &mut AgentView) {
    agent.session.tracker.finish_turn(&mut agent.scrollback);
}
